feat: added module and openapi file for content manager
Sphereon-Opensource/vdx-openapi pull request #2
Opened 2023-08-10 19:13 UTC by sksadjad

2023-08-11 09:18 UTC, BtencateSphereon commented on ecmo/openapi/openapi.yaml
> +        - name: filter
i don't think this should be query but body param, same for all other filters

2023-09-08 09:41 UTC, nklomp requested changes
See remarks.

2023-09-08 09:41 UTC, nklomp commented on ecmo/openapi/openapi.yaml
> +                  $ref: '#/components/schemas/PartyRelationship'
Why does get parties return relationships, but getting a single Party returns a Party?

These should be symetrical

2023-09-08 09:41 UTC, nklomp commented on ecmo/openapi/openapi.yaml
> +        - Contact
Wrong tag

2023-09-08 10:38 UTC, sksadjad commented on ecmo/openapi/openapi.yaml
> +                  $ref: '#/components/schemas/PartyRelationship'
changed this to list of `Party`

2023-09-08 10:38 UTC, sksadjad commented on ecmo/openapi/openapi.yaml
> +        - Contact
changed this tag

2023-09-08 11:27 UTC, nklomp approved these changes
LGTM

2023-09-08 11:31 UTC, merged